<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>McpDotnet</RootNamespace>
    <StartupObject>McpDotnet.Run</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Jint" Version="4.1.0" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="8.0.1" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageReference Include="ModelContextProtocol" Version="0.3.0-preview.4" />
    <PackageReference Include="System.ComponentModel.Annotations" Version="5.0.0" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
    <PackageReference Include="YamlDotNet" Version="16.2.1" />
  </ItemGroup>

  <ItemGroup>
    <None Update="tools/**" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Server.cs" />
    <Compile Remove="tools\lng_batch_run\Stuff\Test.cs" />
  </ItemGroup>

</Project>
